/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'published' : boolean,
  'tags' : Array<string>,
  'excerpt' : string,
}
export interface Message {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'repoUrl' : string,
  'liveUrl' : string,
  'techStack' : Array<string>,
}
export type Time = bigint;
export interface _SERVICE {
  /**
   * / Add a new blog post
   */
  'addBlogPost' : ActorMethod<
    [string, string, string, Array<string>, boolean],
    bigint
  >,
  /**
   * / Add a new message
   */
  'addMessage' : ActorMethod<[string, string, string, string], bigint>,
  /**
   * / Add a new project
   */
  'addProject' : ActorMethod<
    [string, string, Array<string>, string, string],
    bigint
  >,
  /**
   * / Retrieve all messages
   */
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  /**
   * / Retrieve all projects
   */
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  /**
   * / Retrieve blog post by ID
   */
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  /**
   * / Retrieve all published blog posts
   */
  'getPublishedPosts' : ActorMethod<[], Array<BlogPost>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];